# Generated by Django 5.0.6 on 2024-06-05 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ПІБ')),
                ('contact_info', models.CharField(max_length=255, verbose_name='Номер телефону')),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва тендера')),
                ('description', models.TextField(max_length=200, verbose_name='Опис')),
                ('start_date', models.DateField(verbose_name='Дата початку тендера')),
                ('end_date', models.DateField(verbose_name='Дата закінчення тендера')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('terms', models.TextField(verbose_name='Умови')),
                ('submission_date', models.DateField(auto_now_add=True, verbose_name='Дата подання')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учасник')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.tender', verbose_name='Тендер')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Нагорода')),
                ('terms', models.TextField(verbose_name='Умови')),
                ('award_date', models.DateField(auto_now_add=True, verbose_name='Дата нагородження')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учасник')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.tender', verbose_name='Тендер')),
            ],
        ),
        migrations.CreateModel(
            name='TenderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва елемента тендера')),
                ('description', models.TextField(max_length=200, verbose_name='Опис')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Кількість')),
                ('unit', models.CharField(max_length=50, verbose_name='Одиниця')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.tender', verbose_name='Тендер')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
