# Generated by Django 5.0.6 on 2024-06-05 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='index.bidder', verbose_name='Учасник'),
        ),
        migrations.AlterField(
            model_name='award',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='index.tender', verbose_name='Тендер'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='index.bidder', verbose_name='Учасник'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='index.tender', verbose_name='Тендер'),
        ),
        migrations.AlterField(
            model_name='tenderitem',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='index.tender', verbose_name='Тендер'),
        ),
    ]
